service: prodpad-to-twilio # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: handler.ideaToCards
    events:
      - schedule: rate(5 minutes)